In [2]:
import pandas as pd

In [3]:
forum_merged = pd.read_csv('assets/merged/FrequentFlyerForum-Profiles.merged.csv')
pointz_merged = pd.read_csv('assets/merged/PointzAggregator-AirlinesData.xml.merged.csv')

In [21]:
forum_merged['date'] = forum_merged['date'].astype('datetime64[ns]')

In [22]:
forum_merged.drop(['Unnamed: 0', 'account_id'], axis=1, inplace=True)

KeyError: "['Unnamed: 0' 'account_id'] not found in axis"

In [23]:
forum_merged.head()

,sex,first_name,last_name,flight,date,codeshare,country_arrival,city_arrival,airport_arrival,country_departure,city_departure,airport_departure,status,number
0,Male,NaN,NaN,DL3377,2017-03-04,False,United States of,Pittsburgh PA,PIT,United States of,Boston MA,BOS,Basic,KE 889215424
1,Male,NaN,NaN,DL3377,2017-03-04,False,United States of,Pittsburgh PA,PIT,United States of,Boston MA,BOS,Elite+,DT 484697244
2,Male,NaN,NaN,DL3598,2017-07-30,False,United States of,Evansville IN,EVV,United States of,Detroit MI,DTW,Basic,KE 889215424
3,Male,NaN,NaN,DL3598,2017-07-30,False,United States of,Evansville IN,EVV,United States of,Detroit MI,DTW,Elite+,DT 484697244
4,Male,NaN,NaN,DL5498,2017-03-31,False,United States of,Birmingham AI,BHM,United States of,New York NY,LGA,Basic,KE 889215424

In [5]:
pointz_merged.drop(['Unnamed: 0'], axis=1, inplace=True)

In [17]:
pointz_merged['date'] = pointz_merged['date'].astype('datetime64[ns]')

In [20]:
pointz_merged.head()

,first_name,last_name,bonus_program,number,flight_code,date,departure_code,arrival_code,fare
0,IAROMIR,ZVEREV,Flying Blue,FB 171388778,KE827,2017-06-08,rea,SZX,YGRPZT
1,IAROMIR,ZVEREV,Flying Blue,FB 171388778,MU9706,2017-10-26,PEK,BSD,YSTNYV
2,VITALINA,KOROVINA,Korean Air SKYPASS,KE 696768759,DL5058,2017-11-09,CHA,ATL,YRSTKY
3,VITALINA,KOROVINA,Korean Air SKYPASS,KE 696768759,KE1,2017-01-04,rea,HNL,PRSTRU
4,VITALINA,KOROVINA,Korean Air SKYPASS,KE 696768759,DL837,2017-09-13,ATL,HNL,YGRPNG

In [26]:
merged = pd.merge(forum_merged, pointz_merged, how='outer', left_on=['number','flight', 'date'], right_on=['number','flight_code', 'date'])

In [28]:
merged.drop(['bonus_program'], axis=1, inplace=True)

In [29]:
merged

,sex,first_name_x,last_name_x,flight,date,codeshare,country_arrival,city_arrival,airport_arrival,country_departure,city_departure,airport_departure,status,number,first_name_y,last_name_y,flight_code,departure_code,arrival_code,fare
0,Male,NaN,NaN,DL3377,2017-03-04,False,United States of,Pittsburgh PA,PIT,United States of,Boston MA,BOS,Basic,KE 889215424,NaN,NaN,NaN,NaN,NaN,NaN
1,Male,NaN,NaN,DL3377,2017-03-04,False,United States of,Pittsburgh PA,PIT,United States of,Boston MA,BOS,Elite+,DT 484697244,NaN,NaN,NaN,NaN,NaN,NaN
2,Male,NaN,NaN,DL3598,2017-07-30,False,United States of,Evansville IN,EVV,United States of,Detroit MI,DTW,Basic,KE 889215424,NaN,NaN,NaN,NaN,NaN,NaN
3,Male,NaN,NaN,DL3598,2017-07-30,False,United States of,Evansville IN,EVV,United States of,Detroit MI,DTW,Elite+,DT 484697244,NaN,NaN,NaN,NaN,NaN,NaN
4,Male,NaN,NaN,DL5498,2017-03-31,False,United States of,Birmingham AI,BHM,United States of,New York NY,LGA,Basic,KE 889215424,NaN,NaN,NaN,NaN,NaN,NaN
5,Male,NaN,NaN,DL5498,2017-03-31,False,United States of,Birmingham AI,BHM,United States of,New York NY,LGA,Elite+,DT 484697244,NaN,NaN,NaN,NaN,NaN,NaN
6,Male,NaN,NaN,DL659,2017-08-30,False,United States,Fort Lauderdale FL,FLL,United States of,Atlanta GA,ATL,Basic,KE 889215424,NaN,NaN,NaN,NaN,NaN,NaN
7,Male,NaN,NaN,DL659,2017-08-30,False,United States,Fort Lauderdale FL,FLL,United States of,Atlanta GA,ATL,Elite+,DT 484697244,NaN,NaN,NaN,NaN,NaN,NaN
8,Male,NaN,NaN,DL3363,2017-11-10,False,United States of,Jacksonville NC,OAJ,United States of,Atlanta GA,ATL,Basic,KE 889215424,NaN,NaN,NaN,NaN,NaN,NaN
9,Male,NaN,NaN,DL3363,2017-11-10,False,United States of,Jacksonville NC,OAJ,United States of,Atlanta GA,ATL,Elite+,DT 484697244,NaN,NaN,NaN,NaN,NaN,NaN
10,Male,NaN,NaN,DL1364,2017-12-14,False,United States of,Sacramento CA,SMF,United States of,Atlanta GA,ATL,Basic,KE 889215424,NaN,NaN,NaN,NaN,NaN,NaN
11,Male,NaN,NaN,DL1364,2017-12-14,False,United States of,Sacramento CA,SMF,United States of,Atlanta GA,ATL,Elite+,DT 484697244,NaN,NaN,NaN,NaN,NaN,NaN
12,Male,NaN,NaN,DL5435,2017-05-26,False,United States of,Wilmington NC,ILM,United States of,Atlanta GA,ATL,Basic,KE 889215424,NaN,NaN,NaN,NaN,NaN,NaN
13,Male,NaN,NaN,DL5435,2017-05-26,False,United States of,Wilmington NC,ILM,United States of,Atlanta GA,ATL,Elite+,DT 484697244,NaN,NaN,NaN,NaN,NaN,NaN
14,Male,NaN,NaN,DL5558,2017-08-03,False,United States of,Fayetteville AR,XNA,United States of,Atlanta GA,ATL,Basic,KE 889215424,NaN,NaN,NaN,NaN,NaN,NaN
15,Male,NaN,NaN,DL5558,2017-08-03,False,United States of,Fayetteville AR,XNA,United States of,Atlanta GA,ATL,Elite+,DT 484697244,NaN,NaN,NaN,NaN,NaN,NaN
16,Male,NaN,NaN,DL5551,2017-06-24,False,United States of,Shreveport LA,SHV,United States of,Atlanta GA,ATL,Basic,KE 889215424,NaN,NaN,NaN,NaN,NaN,NaN
17,Male,NaN,NaN,DL5551,2017-06-24,False,United States of,Shreveport LA,SHV,United States of,Atlanta GA,ATL,Elite+,DT 484697244,NaN,NaN,NaN,NaN,NaN,NaN
18,Male,NaN,NaN,DL2702,2017-07-20,False,United States of,Green Bay WI,GRB,United States of,Atlanta GA,ATL,Basic,KE 889215424,NaN,NaN,NaN,NaN,NaN,NaN
19,Male,NaN,NaN,DL2702,2017-07-20,False,United States of,Green Bay WI,GRB,United States of,Atlanta GA,ATL,Elite+,DT 484697244,NaN,NaN,NaN,NaN,NaN,NaN
20,Male,NaN,NaN,DL3630,2017-07-21,False,United States of,Detroit MI,DTW,United States of,Green Bay WI,GRB,Basic,KE 889215424,NaN,NaN,NaN,NaN,NaN,NaN
21,Male,NaN,NaN,DL3630,2017-07-21,False,United States of,Detroit MI,DTW,United States of,Green Bay WI,GRB,Elite+,DT 484697244,NaN,NaN,NaN,NaN,NaN,NaN
22,Male,NaN,NaN,DL5361,2017-03-22,False,United States of,New York NY,LGA,United States of,Pittsburgh PA,PIT,Basic,KE 889215424,NaN,NaN,NaN,NaN,NaN,NaN
23,Male,NaN,NaN,DL5361,2017-03-22,False,United States of,New York NY,LGA,United States of,Pittsburgh PA,PIT,Elite+,DT 484697244,NaN,NaN,NaN,NaN,NaN,NaN
24,Male,NaN,NaN,AF3616,2017-02-27,True,United States of,Boston MA,BOS,France,Paris,CDG,Basic,KE 889215424,NaN,NaN,NaN,NaN,NaN,NaN
25,Male,NaN,NaN,AF3616,2017-02-27,True,United States of,Boston MA,BOS,France,Paris,CDG,Elite+,DT 484697244,NaN,NaN,NaN,NaN,NaN,NaN
26,Male,NaN,NaN,DL1726,2017-10-15,False,United States of,Atlanta GA,ATL,United States,Fort Lauderdale FL,FLL,Basic,KE 889215424,NaN,NaN,NaN,NaN,NaN,NaN
27,Male,NaN,NaN,DL1726,2017-10-15,False,United States of,Atlanta GA,ATL,United States,Fort Lauderdale FL,FLL,Elite+,DT 484697244,NaN,NaN,NaN,NaN,NaN,NaN
28,Male,NaN,NaN,DL2596,2017-04-01,False,United States of,Atlanta GA,ATL,United States of,Birmingham AI,BHM,Basic,KE 889215424,NaN,NaN,NaN,NaN,NaN,NaN
29,Male,NaN,NaN,DL2596,2017-04-01,False,United States of,Atlanta GA,ATL,United States of,Birmingham AI,BHM,Elite+,DT 484697244,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2557358,NaN,NaN,NaN,NaN,2017-03-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KE 637084941,EMIL,KAZAKOV,AR1248,AEP,GRU,YFLXAS
2557359,NaN,NaN,NaN,NaN,2017-11-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KE 637084941,EMIL,KAZAKOV,AR7719,GRU,EZE,YFLXOL
2557360,NaN,NaN,NaN,NaN,2017-04-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KE 637084941,EMIL,KAZAKOV,AZ1634,BDS,FCO,YGRPVZ
2557361,NaN,NaN,NaN,NaN,2017-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KE 637084941,EMIL,KAZAKOV,SU6402,SVX,LED,YGRPPM
2557362,NaN,NaN,NaN,NaN,2017-12-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KE 637084941,EMIL,KAZAKOV,AR1142,EZE,FCO,PRSTQA
2557363,NaN,NaN,NaN,NaN,2017-09-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KE 637084941,EMIL,KAZAKOV,AR1143,FCO,EZE,YGRPFA
2557364,NaN,NaN,NaN,NaN,2017-10-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DT 269347755,EMIL,KAZAKOV,AR1874,EZE,FTE,YGRPAF
2557365,NaN,NaN,NaN,NaN,2017-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DT 269347755,EMIL,KAZAKOV,UX3291,SVO,AGP,YFLXRJ
2557366,NaN,NaN,NaN,NaN,2017-11-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DT 269347755,EMIL,KAZAKOV,AR2805,FTE,AEP,YFLXMR
2557367,NaN,NaN,NaN,NaN,2017-02-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DT 269347755,EMIL,KAZAKOV,SU6401,LED,SVX,YFLXZR
2557368,NaN,NaN,NaN,NaN,2017-09-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DT 269347755,EMIL,KAZAKOV,AZ91,AGP,FCO,YSTNCI
2557369,NaN,NaN,NaN,NaN,2017-03-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DT 269347755,EMIL,KAZAKOV,AR1248,AEP,GRU,YFLXAS
2557370,NaN,NaN,NaN,NaN,2017-11-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DT 269347755,EMIL,KAZAKOV,AR7719,GRU,EZE,YFLXOL
2557371,NaN,NaN,NaN,NaN,2017-04-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DT 269347755,EMIL,KAZAKOV,AZ1634,BDS,FCO,YGRPVZ
2557372,NaN,NaN,NaN,NaN,2017-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DT 269347755,EMIL,KAZAKOV,SU6402,SVX,LED,YGRPPM
2557373,NaN,NaN,NaN,NaN,2017-12-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DT 269347755,EMIL,KAZAKOV,AR1142,EZE,FCO,PRSTQA
2557374,NaN,NaN,NaN,NaN,2017-09-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DT 269347755,EMIL,KAZAKOV,AR1143,FCO,EZE,YGRPFA
2557375,NaN,NaN,NaN,NaN,2017-10-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SU 856232932,EMIL,KAZAKOV,AR1874,EZE,FTE,YGRPAF
2557376,NaN,NaN,NaN,NaN,2017-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SU 856232932,EMIL,KAZAKOV,UX3291,SVO,AGP,YFLXRJ
2557377,NaN,NaN,NaN,NaN,2017-11-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SU 856232932,EMIL,KAZAKOV,AR2805,FTE,AEP,YFLXMR
2557378,NaN,NaN,NaN,NaN,2017-02-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SU 856232932,EMIL,KAZAKOV,SU6401,LED,SVX,YFLXZR
2557379,NaN,NaN,NaN,NaN,2017-09-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SU 856232932,EMIL,KAZAKOV,AZ91,AGP,FCO,YSTNCI
2557380,NaN,NaN,NaN,NaN,2017-03-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SU 856232932,EMIL,KAZAKOV,AR1248,AEP,GRU,YFLXAS
2557381,NaN,NaN,NaN,NaN,2017-11-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SU 856232932,EMIL,KAZAKOV,AR7719,GRU,EZE,YFLXOL
2557382,NaN,NaN,NaN,NaN,2017-04-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SU 856232932,EMIL,KAZAKOV,AZ1634,BDS,FCO,YGRPVZ
2557383,NaN,NaN,NaN,NaN,2017-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SU 856232932,EMIL,KAZAKOV,SU6402,SVX,LED,YGRPPM
2557384,NaN,NaN,NaN,NaN,2017-12-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SU 856232932,EMIL,KAZAKOV,AR1142,EZE,FCO,PRSTQA
2557385,NaN,NaN,NaN,NaN,2017-09-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SU 856232932,EMIL,KAZAKOV,AR1143,FCO,EZE,YGRPFA
2557386,NaN,NaN,NaN,NaN,2017-12-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DT 302785701,UL'YANA,KONONOVA,GA502,CGK,PNK,YFLXAU
2557387,NaN,NaN,NaN,NaN,2017-02-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DT 302785701,UL'YANA,KONONOVA,GA88,CGK,AMS,YRSTQC

In [31]:
first_name_x_null = merged.first_name_x.isnull()
last_name_x_null = merged.last_name_x.isnull()
merged.loc[merged[first_name_x_null].index, 'first_name_x'] = merged.loc[merged[first_name_x_null].index, 'first_name_y']
merged.loc[merged[last_name_x_null].index, 'last_name_x'] = merged.loc[merged[last_name_x_null].index, 'last_name_y']

In [33]:
merged.drop(['first_name_y', 'last_name_y'], axis=1, inplace=True)

In [35]:
flight_null = merged.flight.isnull()
merged.loc[merged[flight_null].index, 'flight'] = merged.loc[merged[flight_null].index, 'flight_code']

In [37]:
merged.drop(['flight_code'], axis=1, inplace=True)

In [39]:
airport_arrival_null = merged.airport_arrival.isnull()
airport_departure_null = merged.airport_departure.isnull()
merged.loc[merged[airport_arrival_null].index, 'airport_arrival'] = merged.loc[merged[airport_arrival_null].index, 'arrival_code']
merged.loc[merged[airport_departure_null].index, 'airport_departure'] = merged.loc[merged[airport_departure_null].index, 'departure_code']

In [41]:
merged.drop(['departure_code', 'arrival_code'], axis=1, inplace=True)

In [42]:
merged.rename(columns={'first_name_x': 'first_name', 'last_name_x': 'last_name'}, inplace=True)

In [44]:
merged.to_csv('assets/merged/forum_pointz.merged.csv')